// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AppStorageInterface is an autogenerated mock type for the AppStorageInterface type
type AppStorageInterface struct {
	mock.Mock
}

// Get provides a mock function with given fields: key
func (_m *AppStorageInterface) Get(key string) (string, error) {
	ret := _m.Called(key)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: key, value
func (_m *AppStorageInterface) Set(key string, value string) error {
	ret := _m.Called(key, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewAppStorageInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewAppStorageInterface creates a new instance of AppStorageInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAppStorageInterface(t mockConstructorTestingTNewAppStorageInterface) *AppStorageInterface {
	mock := &AppStorageInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
