// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// InterfaceAppService is an autogenerated mock type for the InterfaceAppService type
type InterfaceAppService struct {
	mock.Mock
}

// GenerateShortURL provides a mock function with given fields:
func (_m *InterfaceAppService) GenerateShortURL() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// URLGetID provides a mock function with given fields: url
func (_m *InterfaceAppService) URLGetID(url string) (string, error) {
	ret := _m.Called(url)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(url)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// URLShorter provides a mock function with given fields: url
func (_m *InterfaceAppService) URLShorter(url string) (string, error) {
	ret := _m.Called(url)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(url)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewInterfaceAppService interface {
	mock.TestingT
	Cleanup(func())
}

// NewInterfaceAppService creates a new instance of InterfaceAppService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewInterfaceAppService(t mockConstructorTestingTNewInterfaceAppService) *InterfaceAppService {
	mock := &InterfaceAppService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
