// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// InterfaceAppHandler is an autogenerated mock type for the InterfaceAppHandler type
type InterfaceAppHandler struct {
	mock.Mock
}

// RunServer provides a mock function with given fields:
func (_m *InterfaceAppHandler) RunServer() {
	_m.Called()
}

// URLGetID provides a mock function with given fields: w, r
func (_m *InterfaceAppHandler) URLGetID(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// URLShortener provides a mock function with given fields: w, r
func (_m *InterfaceAppHandler) URLShortener(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

type mockConstructorTestingTNewInterfaceAppHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewInterfaceAppHandler creates a new instance of InterfaceAppHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewInterfaceAppHandler(t mockConstructorTestingTNewInterfaceAppHandler) *InterfaceAppHandler {
	mock := &InterfaceAppHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
